<a href="https://colab.research.google.com/github/oshaajayaweera/Databases-and-Analytics/blob/main/01_SQL_in_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
install.packages("sqldf")
install.packages("dplyr")
install.packages("ggplot2")

library(sqldf)
library(dplyr)
library(ggplot2)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
base_url <- "https://raw.githubusercontent.com/oshaajayaweera/Databases-and-Analytics/main/"

customers <- read.csv(paste0(base_url, "customers.csv"))
orders <- read.csv(paste0(base_url, "orders.csv"))
deliveries <- read.csv(paste0(base_url, "deliveries.csv"))
drivers <- read.csv(paste0(base_url, "drivers.csv"))
vehicles <- read.csv(paste0(base_url, "vehicles.csv"))
hubs <- read.csv(paste0(base_url, "hubs.csv"))
complaints <- read.csv(paste0(base_url, "complaints.csv"))
incidents <- read.csv(paste0(base_url, "incidents.csv"))
app_events <- read.csv(paste0(base_url, "app_events.csv"))
data_dictionary <- read.csv(paste0(base_url, "data_dictionary.csv"))

In [3]:
head(deliveries)
str(deliveries)
head(orders)
head(hubs)

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
6 2024-09-12 17:11:52.384869 Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

'data.frame':	950 obs. of  13 variables:
 $ delivery_id                  : chr  "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr  "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr  "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr  "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr  "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : chr  "2024-06-18 10:57:00" "2025-01-11 18:45:00" "2025-06-02 20:39:00" "2024-03-08 23:31:00" ...
 $ delivery_completed_at        : chr  "2024-06-19 09:05:59.904311" "2025-01-11 17:39:00.000000" "2025-06-02 21:45:32.366770" "2024-03-09 23:30:08.103702" ...
 $ delivery_status              : chr  "Failed" "OnTime" "OnTime" "Delayed" ...
 $ route_distance_km            : num  17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : int  1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num  3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num  12.05 13.41 8.51 13.62 9.22 ...

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
6 O00006   C0437       Retail       2024-08-05 04:55:00  1
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       AIRPORT      Low            109.30      App
3 West        AIRPORT      High            33.50      Phone
4 RiverSide   North        Medium          10.04      App
5 Riverside   SOUTH        Low            125.58      Phone
6 CENTRAL     East         High           151.44      Web
  special_handling_flag
1 0
2 0
3 0
4 1
5 0
6 1

  hub_id hub_name       zone    hub_type  capacity_score
1 H01    North Exchange North   Dispatch  82
2 H02    South Link     South   Dispatch  78
3 H03    East Dock      East    Warehouse 74
4 H04    West Gate      West    Dispatch  69
5 H05    Central Core   Central Control   88
6 H06    Airport Hub    Airport Dispatch  71

In [4]:
query1 <- sqldf("
SELECT
    delivery_id,
    order_id,
    driver_id,
    hub_id,
    dispatch_time,
    delivery_completed_at,
    delivery_status,
    ROUND((julianday(delivery_completed_at) - julianday(dispatch_time)) * 1440, 2) AS delivery_minutes
FROM deliveries
WHERE delivery_completed_at IS NOT NULL
  AND dispatch_time IS NOT NULL
  AND ROUND((julianday(delivery_completed_at) - julianday(dispatch_time)) * 1440, 2) > 60
ORDER BY delivery_minutes DESC
")

query1

    delivery_id order_id driver_id hub_id dispatch_time
1   DL00386     O00135   D144      H05    2025-04-25 03:12:00
2   DL00387     O00274   D016      H01    2025-10-03 21:33:00
3   DL00033     O00885   D041      H06    2024-11-17 14:01:00
4   DL00530     O00756   D095      H01    2025-02-03 18:06:00
5   DL00026     O00906   D092      H04    2025-02-04 11:16:00
6   DL00806     O00128   D117      H07    2025-12-28 14:40:00
7   DL00497     O00192   D083      H08    2025-08-18 14:17:00
8   DL00472     O00042   D113      H01    2025-12-01 19:10:00
9   DL00775     O00153   D109      H05    2025-02-09 09:08:00
10  DL00068     O00828   D104      H08    2024-02-19 15:15:00
11  DL00763     O00837   D110      H02    2024-04-18 19:06:00
12  DL00658     O01123   D001      H04    2024-01-31 07:38:00
13  DL00269     O00131   D085      H06    2024-06-29 23:38:00
14  DL00007     O00097   D151      H07    2024-01-09 13:41:00
15  DL00512     O00224   D040      H07    2024-05-22 23:18:00
16  DL00359     O00654   D068      H01    2025-06-18 22:44:00
17  DL00893     O00981   D062      H05    2025-01-11 23:09:00
18  DL00732     O00748   D024      H01    2025-07-23 06:45:00
19  DL00684     O00986   D026      H08    2024-02-06 11:40:00
20  DL00838     O00909   D117      H03    2025-01-05 03:05:00
21  DL00369     O00366   D011      H05    2024-02-12 22:37:00
22  DL00119     O01011   D076      H03    2024-02-28 07:57:00
23  DL00184     O01005   D023      H07    2025-05-01 19:42:00
24  DL00173     O00459   D131      H08    2025-11-28 08:52:00
25  DL00701     O00440   D077      H08    2024-12-03 03:36:00
26  DL00690     O00129   D167      H01    2024-12-12 05:16:00
27  DL00645     O00158   D129      H02    2024-07-11 17:47:00
28  DL00126     O00547   D159      H07    2024-04-09 14:36:00
29  DL00862     O00031   D165      H01    2024-10-25 04:57:00
30  DL00006     O00029   D037      H03    2024-09-11 12:40:00
⋮   ⋮           ⋮        ⋮         ⋮      ⋮
789 DL00461     O00862   D089      H08    2025-01-29 15:08:00
790 DL00624     O00486   D110      H02    2024-08-12 17:01:00
791 DL00649     O00110   D075      H01    2024-08-23 13:10:00
792 DL00848     O00633   D080      H08    2024-02-12 13:23:00
793 DL00598     O00753   D056      H02    2025-01-18 05:04:00
794 DL00274     O01198   D080      H02    2025-01-13 05:25:00
795 DL00253     O00325   D126      H08    2024-09-30 05:43:00
796 DL00733     O00252   D009      H03    2024-03-10 16:48:00
797 DL00108     O00620   D084      H06    2024-11-08 01:38:00
798 DL00535     O01058   D033      H07    2025-05-09 00:57:00
799 DL00867     O01117   D089      H02    2025-06-20 01:47:00
800 DL00023     O00768   D046      H08    2025-06-12 01:16:00
801 DL00154     O00071   D018      H08    2024-09-01 00:47:00
802 DL00556     O00702   D070      H07    2024-12-28 22:07:00
803 DL00599     O01150   D133      H01    2025-02-20 06:18:00
804 DL00489     O00911   D130      H02    2025-05-20 23:09:00
805 DL00221     O00594   D151      H02    2024-03-11 21:43:00
806 DL00491     O00181   D124      H08    2024-12-16 02:36:00
807 DL00340     O00435   D086      H05    2024-09-19 13:43:00
808 DL00662     O00365   D118      H03    2024-01-11 13:00:00
809 DL00362     O00460   D156      H04    2024-12-09 18:44:00
810 DL00101     O00354   D141      H06    2025-12-02 18:06:00
811 DL00038     O00727   D096      H02    2025-10-26 15:31:00
812 DL00710     O00262   D116      H06    2024-02-28 06:22:00
813 DL00452     O00468   D125      H01    2024-03-29 12:52:00
814 DL00584     O00588   D043      H05    2024-06-03 13:36:00
815 DL00829     O00426   D101      H03    2024-09-28 15:10:00
816 DL00299     O01061   D121      H07    2024-04-29 22:39:00
817 DL00003     O00639   D006      H02    2025-06-02 20:39:00
818 DL00107     O00175   D120      H05    2025-12-19 20:22:00
    delivery_completed_at      delivery_status delivery_minutes
1   2025-04-26 22:39:24.905513 Failed          2607.42
2   2025-10-05 15:40:35.899437 Failed          2527.60
3   2024-11-19 06:51:25.201294 Failed          2450.42
4   2025-02-05 09:39:56.840261 Failed          2373.95
5   2025-02-06 01:48:45.831712 Failed          2312.76
6   2025-12-30 04:18:53.684717 Delayed         2258.89
7   2025-08-20 03:34:36.170242 Failed          2237.60
8   2025-12-03 08:16:03.110618 Delayed         2226.05
9   2025-02-10 21:51:56.051970 Delayed         2203.93
10  2024-02-21 03:47:37.311854 Failed          2192.62
11  2024-04-20 06:31:48.519667 Failed          2125.81
12  2024-02-01 18:27:27.869371 Failed          2089.46
13  2024-07-01 10:09:10.323380 Delayed         2071.17
14  2024-01-10 23:39:11.072850 Delayed         2038.18
15  2024-05-24 08:58:29.649915 Delayed         2020.49
16  2025-06-20 08:19:56.137076 Delayed         2015.94
17  2025-01-13 08:12:13.529331 Delayed         1983.23
18  2025-07-24 15:06:33.826133 Failed          1941.56
19  2024-02-07 19:38:29.699653 Delayed         1918.50
20  2025-01-06 10:48:03.226335 Failed          1903.05
21  2024-02-14 06:15:16.530828 Delayed         1898.28
22  2024-02-29 14:55:52.373220 Failed          1858.87
23  2025-05-03 02:37:43.403054 Failed          1855.72
24  2025-11-29 15:17:47.295669 Delayed         1825.79
25  2024-12-04 09:00:24.432584 Failed          1764.41
26  2024-12-13 10:27:02.080765 Failed          1751.03
27  2024-07-12 22:44:12.693757 Failed          1737.21
28  2024-04-10 19:11:28.149157 Delayed         1715.47
29  2024-10-26 09:32:20.877141 Failed          1715.35
30  2024-09-12 17:11:52.384869 Delayed         1711.87
⋮   ⋮                          ⋮               ⋮
789 2025-01-29 16:46:22.767038 OnTime          98.38
790 2024-08-12 18:38:04.590348 OnTime          97.08
791 2024-08-23 14:46:36.192013 OnTime          96.60
792 2024-02-12 14:55:42.792793 OnTime          92.71
793 2025-01-18 06:33:32.191118 OnTime          89.54
794 2025-01-13 06:53:29.209324 OnTime          88.49
795 2024-09-30 07:09:22.633894 OnTime          86.38
796 2024-03-10 18:13:36.725392 OnTime          85.61
797 2024-11-08 03:02:54.779512 OnTime          84.91
798 2025-05-09 02:20:23.931566 OnTime          83.40
799 2025-06-20 03:09:47.164152 OnTime          82.79
800 2025-06-12 02:37:11.392658 OnTime          81.19
801 2024-09-01 02:07:26.317027 Failed          80.44
802 2024-12-28 23:26:56.318304 OnTime          79.94
803 2025-02-20 07:36:40.669805 OnTime          78.68
804 2025-05-21 00:26:05.202498 OnTime          77.09
805 2024-03-11 22:58:44.220273 OnTime          75.74
806 2024-12-16 03:51:28.734813 OnTime          75.48
807 2024-09-19 14:58:25.664734 OnTime          75.43
808 2024-01-11 14:14:42.407650 OnTime          74.71
809 2024-12-09 19:57:19.363281 OnTime          73.32
810 2025-12-02 19:18:47.006775 OnTime          72.78
811 2025-10-26 16:43:11.478296 Failed          72.19
812 2024-02-28 07:32:37.271724 OnTime          70.62
813 2024-03-29 14:01:48.798026 OnTime          69.81
814 2024-06-03 14:45:41.100373 OnTime          69.68
815 2024-09-28 16:18:55.493540 OnTime          68.92
816 2024-04-29 23:45:53.493983 OnTime          66.89
817 2025-06-02 21:45:32.366770 OnTime          66.54
818 2025-12-19 21:26:01.755844 OnTime          64.03

In [5]:
query2 <- sqldf("
SELECT
    delivery_id,
    order_id,
    driver_id,
    hub_id,
    vehicle_id,
    delivery_status
FROM deliveries
WHERE delivery_status = 'Failed'
")

query2

    delivery_id order_id driver_id hub_id vehicle_id delivery_status
1   DL00001     O00938   D004      H05    V056       Failed
2   DL00010     O00836   D058      H08    V057       Failed
3   DL00012     O01207   D051      H05    V017       Failed
4   DL00022     O01027   D088      H07    V011       Failed
5   DL00026     O00906   D092      H04    V055       Failed
6   DL00033     O00885   D041      H06    V075       Failed
7   DL00038     O00727   D096      H02    V002       Failed
8   DL00039     O00542   D090      H08    V034       Failed
9   DL00040     O00919   D027      H04    V036       Failed
10  DL00041     O00750   D100      H08    V057       Failed
11  DL00057     O00921   D141      H04    V077       Failed
12  DL00068     O00828   D104      H08    V046       Failed
13  DL00069     O01039   D010      H07    V074       Failed
14  DL00074     O01195   D030      H04    V092       Failed
15  DL00078     O00173   D144      H02    V088       Failed
16  DL00084     O00784   D063      H05    V117       Failed
17  DL00089     O00241   D010      H03    V112       Failed
18  DL00097     O00794   D170      H07    V109       Failed
19  DL00098     O00631   D004      H07    V072       Failed
20  DL00100     O00205   D120      H05    V097       Failed
21  DL00103     O00269   D004      H04    V036       Failed
22  DL00118     O00660   D143      H01    V004       Failed
23  DL00119     O01011   D076      H03    V037       Failed
24  DL00135     O00225   D069      H03    V075       Failed
25  DL00153     O00893   D115      H01    V007       Failed
26  DL00154     O00071   D018      H08    V110       Failed
27  DL00166     O00904   D091      H04    V017       Failed
28  DL00167     O00932   D116      H08    V069       Failed
29  DL00178     O01166   D024      H05    V052       Failed
30  DL00184     O01005   D023      H07    V096       Failed
⋮   ⋮           ⋮        ⋮         ⋮      ⋮          ⋮
103 DL00745     O00333   D092      H07    V072       Failed
104 DL00763     O00837   D110      H02    V059       Failed
105 DL00766     O00371   D082      H07    V088       Failed
106 DL00778     O00965   D143      H08    V005       Failed
107 DL00781     O00871   D082      H02    V092       Failed
108 DL00783     O00380   D099      H07    V015       Failed
109 DL00788     O00927   D108      H05    V058       Failed
110 DL00789     O00536   D103      H06    V031       Failed
111 DL00792     O00033   D106      H08    V094       Failed
112 DL00807     O00089   D103      H05    V061       Failed
113 DL00823     O00655   D104      H08    V114       Failed
114 DL00824     O00369   D036      H02    V080       Failed
115 DL00825     O01004   D147      H05    V007       Failed
116 DL00831     O00023   D133      H08    V053       Failed
117 DL00832     O01143   D083      H06    V109       Failed
118 DL00836     O00206   D095      H01    V057       Failed
119 DL00838     O00909   D117      H03    V103       Failed
120 DL00839     O00566   D078      H03    V096       Failed
121 DL00862     O00031   D165      H01    V037       Failed
122 DL00868     O00452   D104      H04    V100       Failed
123 DL00888     O01129   D055      H07    V027       Failed
124 DL00889     O01172   D105      H08    V002       Failed
125 DL00906     O01229   D168      H08    V110       Failed
126 DL00920     O00686   D133      H03    V034       Failed
127 DL00921     O00332   D063      H08    V108       Failed
128 DL00928     O00100   D023      H05    V101       Failed
129 DL00931     O01171   D006      H08    V062       Failed
130 DL00935     O00211   D107      H08    V012       Failed
131 DL00938     O01246   D132      H03    V109       Failed
132 DL00942     O01112   D013      H04    V027       Failed

In [6]:
query3 <- sqldf("
SELECT
    hub_id,
    COUNT(delivery_id) AS total_deliveries,
    SUM(CASE WHEN delivery_status = 'Delayed' THEN 1 ELSE 0 END) AS delayed_deliveries,
    SUM(CASE WHEN delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries
FROM deliveries
GROUP BY hub_id
ORDER BY failed_deliveries DESC, delayed_deliveries DESC
")

query3

  hub_id total_deliveries delayed_deliveries failed_deliveries
1 H08    128              22                 26
2 H05    115              25                 23
3 H01    136              26                 17
4 H04    127              28                 16
5 H06    104              27                 15
6 H07    115              25                 14
7 H03    119              23                 11
8 H02    106              26                 10

In [7]:
query4 <- sqldf("
SELECT
    hub_id,
    ROUND(AVG(manual_route_override_count), 2) AS avg_route_overrides,
    ROUND(AVG(route_distance_km), 2) AS avg_route_distance
FROM deliveries
GROUP BY hub_id
ORDER BY avg_route_overrides DESC
")

query4

  hub_id avg_route_overrides avg_route_distance
1 H08    1.11                12.82
2 H07    1.05                14.29
3 H01    1.03                13.64
4 H05    0.95                14.32
5 H02    0.92                14.17
6 H06    0.91                14.41
7 H03    0.89                14.52
8 H04    0.87                13.38

In [8]:
query4 <- sqldf("
SELECT
    hub_id,
    ROUND(AVG(manual_route_override_count), 2) AS avg_route_overrides,
    ROUND(AVG(route_distance_km), 2) AS avg_route_distance
FROM deliveries
GROUP BY hub_id
ORDER BY avg_route_overrides DESC
")

query4

  hub_id avg_route_overrides avg_route_distance
1 H08    1.11                12.82
2 H07    1.05                14.29
3 H01    1.03                13.64
4 H05    0.95                14.32
5 H02    0.92                14.17
6 H06    0.91                14.41
7 H03    0.89                14.52
8 H04    0.87                13.38

In [9]:
query5 <- sqldf("
SELECT
    delivery_status,
    ROUND(AVG(fuel_or_charge_cost), 2) AS avg_fuel_charge_cost
FROM deliveries
GROUP BY delivery_status
ORDER BY avg_fuel_charge_cost DESC
")

query5

  delivery_status avg_fuel_charge_cost
1 Failed          13.15
2 Delayed         13.14
3 OnTime          12.68